import { Expense } from "../types";

export const mockExpenses: Expense[] = [
  // e001 — Mess / Catering → Hostel Expense / Grocery
  { id: "e001", vendorId: "v001", category: "Mess / Catering", amount: 85000, cgst: 4250, sgst: 4250, igst: 0, invoiceNumber: "MTC/2024-25/0123", invoiceFile: "invoice_0123.pdf", date: "2024-09-05", description: "Hostel mess charges - August 2024", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "Hostel Expense", accountSubHead: "Grocery" },
  // e002 — Lab Supplies → College Expense / Purchase / Lab Consumables
  { id: "e002", vendorId: "v002", category: "Lab Supplies", amount: 28500, cgst: 1425, sgst: 1425, igst: 0, invoiceNumber: "SLS/2024/0456", invoiceFile: "invoice_0456.pdf", date: "2024-09-12", description: "Anatomy lab consumables - Q2", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "Purchase", accountLeaf: "Lab Consumables" },
  // e003 — Stationery (office) → College Expense / Purchase / Stationery
  { id: "e003", vendorId: "v003", category: "Stationery", amount: 12000, cgst: 600, sgst: 600, igst: 0, invoiceNumber: "NSW/2024/0078", invoiceFile: "invoice_0078.pdf", date: "2024-09-18", description: "Office stationery and printing paper", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "Purchase", accountLeaf: "Stationery" },
  // e004 — Electricity → College Expense / Miscellaneous / Electric Bill
  { id: "e004", vendorId: "v007", category: "Electricity", amount: 34200, cgst: 0, sgst: 0, igst: 0, invoiceNumber: "CESC/OCT/2024", invoiceFile: "cesc_oct.pdf", date: "2024-10-08", description: "CESC electricity bill - October 2024", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "Miscellaneous", accountLeaf: "Electric Bill" },
  // e005 — Mess / Catering → Hostel Expense / Grocery
  { id: "e005", vendorId: "v001", category: "Mess / Catering", amount: 88000, cgst: 4400, sgst: 4400, igst: 0, invoiceNumber: "MTC/2024-25/0145", invoiceFile: "invoice_0145.pdf", date: "2024-10-05", description: "Hostel mess charges - September 2024", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "Hostel Expense", accountSubHead: "Grocery" },
  // e006 — Telecommunications → College Expense / Miscellaneous / Visit Expenses
  { id: "e006", vendorId: "v006", category: "Telecommunications", amount: 5800, cgst: 522, sgst: 522, igst: 0, invoiceNumber: "BSNL/OCT/2024", invoiceFile: "bsnl_oct.pdf", date: "2024-10-10", description: "BSNL broadband and telephone - October 2024", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "Miscellaneous", accountLeaf: "Visit Expenses" },
  // e007 — Printing (admit cards/exam) → College Expense / Purchase / Stationery
  { id: "e007", vendorId: "v009", category: "Printing", amount: 22500, cgst: 1125, sgst: 1125, igst: 0, invoiceNumber: "MP/2024/0234", invoiceFile: "invoice_0234.pdf", date: "2024-10-15", description: "Admit cards and hall tickets printing - Term 1", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "Purchase", accountLeaf: "Stationery" },
  // e008 — Clinical Posting → College Expense / College Paperwork / Eco Hospital
  { id: "e008", vendorId: "v004", category: "Clinical Posting", amount: 45000, cgst: 2250, sgst: 2250, igst: 0, invoiceNumber: "AMRI/2024/1089", invoiceFile: "amri_1089.pdf", date: "2024-10-20", description: "Clinical posting charges Q2 - AMRI Dhakuria", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "College Paperwork", accountLeaf: "Eco Hospital" },
  // e009 — Pharmacy / Medical → Hostel Expense / Medicine
  { id: "e009", vendorId: "v008", category: "Pharmacy / Medical", amount: 18750, cgst: 937, sgst: 937, igst: 0, invoiceNumber: "EP/2024/0567", invoiceFile: "ep_0567.pdf", date: "2024-11-02", description: "First aid and emergency medicines stock", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "Hostel Expense", accountSubHead: "Medicine" },
  // e010 — Mess / Catering → Hostel Expense / Grocery
  { id: "e010", vendorId: "v001", category: "Mess / Catering", amount: 91000, cgst: 4550, sgst: 4550, igst: 0, invoiceNumber: "MTC/2024-25/0167", invoiceFile: "invoice_0167.pdf", date: "2024-11-05", description: "Hostel mess charges - October 2024", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "Hostel Expense", accountSubHead: "Grocery" },
  // e011 — Security → College Expense / Purchase / Office Supplies
  { id: "e011", vendorId: "v010", category: "Security", amount: 32000, cgst: 1600, sgst: 1600, igst: 0, invoiceNumber: "GS/2024/0890", invoiceFile: "gs_0890.pdf", date: "2024-11-01", description: "Security services - November 2024", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "Purchase", accountLeaf: "Office Supplies" },
  // e012 — Electricity → College Expense / Miscellaneous / Electric Bill
  { id: "e012", vendorId: "v007", category: "Electricity", amount: 38500, cgst: 0, sgst: 0, igst: 0, invoiceNumber: "CESC/NOV/2024", invoiceFile: "cesc_nov.pdf", date: "2024-11-08", description: "CESC electricity bill - November 2024", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "Miscellaneous", accountLeaf: "Electric Bill" },
  // e013 — Lab Supplies → College Expense / Purchase / Lab Consumables
  { id: "e013", vendorId: "v002", category: "Lab Supplies", amount: 32000, cgst: 1600, sgst: 1600, igst: 0, invoiceNumber: "SLS/2024/0512", invoiceFile: "invoice_0512.pdf", date: "2024-11-14", description: "Microbiology lab consumables", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "Purchase", accountLeaf: "Lab Consumables" },
  // e014 — Clinical Posting → College Expense / College Paperwork / Eco Hospital
  { id: "e014", vendorId: "v005", category: "Clinical Posting", amount: 38000, cgst: 1900, sgst: 1900, igst: 0, invoiceNumber: "ILS/2024/0456", invoiceFile: "ils_0456.pdf", date: "2024-11-20", description: "Clinical posting charges Q2 - ILS Howrah", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "College Paperwork", accountLeaf: "Eco Hospital" },
  // e015 — Mess / Catering → Hostel Expense / Grocery
  { id: "e015", vendorId: "v001", category: "Mess / Catering", amount: 89000, cgst: 4450, sgst: 4450, igst: 0, invoiceNumber: "MTC/2024-25/0189", invoiceFile: "invoice_0189.pdf", date: "2024-12-05", description: "Hostel mess charges - November 2024", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "Hostel Expense", accountSubHead: "Grocery" },
  // e016 — Electricity → College Expense / Miscellaneous / Electric Bill
  { id: "e016", vendorId: "v007", category: "Electricity", amount: 41200, cgst: 0, sgst: 0, igst: 0, invoiceNumber: "CESC/DEC/2024", invoiceFile: "cesc_dec.pdf", date: "2024-12-08", description: "CESC electricity bill - December 2024", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "Miscellaneous", accountLeaf: "Electric Bill" },
  // e017 — Telecommunications → College Expense / Miscellaneous / Visit Expenses
  { id: "e017", vendorId: "v006", category: "Telecommunications", amount: 5900, cgst: 531, sgst: 531, igst: 0, invoiceNumber: "BSNL/DEC/2024", invoiceFile: "bsnl_dec.pdf", date: "2024-12-10", description: "BSNL broadband and telephone - December 2024", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "Miscellaneous", accountLeaf: "Visit Expenses" },
  // e018 — Security → College Expense / Purchase / Office Supplies
  { id: "e018", vendorId: "v010", category: "Security", amount: 32000, cgst: 1600, sgst: 1600, igst: 0, invoiceNumber: "GS/2024/0934", invoiceFile: "gs_0934.pdf", date: "2024-12-01", description: "Security services - December 2024", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "Purchase", accountLeaf: "Office Supplies" },
  // e019 — Stationery (office) → College Expense / Purchase / Stationery
  { id: "e019", vendorId: "v003", category: "Stationery", amount: 8500, cgst: 425, sgst: 425, igst: 0, invoiceNumber: "NSW/2024/0145", invoiceFile: "invoice_0145.pdf", date: "2024-12-18", description: "Year-end stationery stock replenishment", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "Purchase", accountLeaf: "Stationery" },
  // e020 — Printing (calendar/prospectus) → College Expense / Advertisement / Offline Advertisement
  { id: "e020", vendorId: "v009", category: "Printing", amount: 15000, cgst: 750, sgst: 750, igst: 0, invoiceNumber: "MP/2024/0312", invoiceFile: "invoice_0312.pdf", date: "2024-12-20", description: "Annual calendar and prospectus printing", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "Advertisement", accountLeaf: "Offline Advertisement" },
  // e021 — Mess / Catering → Hostel Expense / Grocery
  { id: "e021", vendorId: "v001", category: "Mess / Catering", amount: 92000, cgst: 4600, sgst: 4600, igst: 0, invoiceNumber: "MTC/2024-25/0201", invoiceFile: "invoice_0201.pdf", date: "2025-01-05", description: "Hostel mess charges - December 2024", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "Hostel Expense", accountSubHead: "Grocery" },
  // e022 — Electricity → College Expense / Miscellaneous / Electric Bill
  { id: "e022", vendorId: "v007", category: "Electricity", amount: 39800, cgst: 0, sgst: 0, igst: 0, invoiceNumber: "CESC/JAN/2025", invoiceFile: "cesc_jan.pdf", date: "2025-01-08", description: "CESC electricity bill - January 2025", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "Miscellaneous", accountLeaf: "Electric Bill" },
  // e023 — Lab Supplies → College Expense / Purchase / Lab Consumables
  { id: "e023", vendorId: "v002", category: "Lab Supplies", amount: 41000, cgst: 2050, sgst: 2050, igst: 0, invoiceNumber: "SLS/2025/0034", invoiceFile: "invoice_0034.pdf", date: "2025-01-14", description: "Pharmacology lab supplies Q3", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "Purchase", accountLeaf: "Lab Consumables" },
  // e024 — Pharmacy / Medical → Hostel Expense / Medicine
  { id: "e024", vendorId: "v008", category: "Pharmacy / Medical", amount: 21500, cgst: 1075, sgst: 1075, igst: 0, invoiceNumber: "EP/2025/0045", invoiceFile: "ep_0045.pdf", date: "2025-01-22", description: "Nursing supplies and consumables restock", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "Hostel Expense", accountSubHead: "Medicine" },
  // e025 — Security → College Expense / Purchase / Office Supplies
  { id: "e025", vendorId: "v010", category: "Security", amount: 32000, cgst: 1600, sgst: 1600, igst: 0, invoiceNumber: "GS/2025/0012", invoiceFile: "gs_0012.pdf", date: "2025-02-01", description: "Security services - February 2025", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "Purchase", accountLeaf: "Office Supplies" },
  // e026 — Mess / Catering → Hostel Expense / Grocery
  { id: "e026", vendorId: "v001", category: "Mess / Catering", amount: 87000, cgst: 4350, sgst: 4350, igst: 0, invoiceNumber: "MTC/2024-25/0225", invoiceFile: "invoice_0225.pdf", date: "2025-02-05", description: "Hostel mess charges - January 2025", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "Hostel Expense", accountSubHead: "Grocery" },
  // e027 — Electricity → College Expense / Miscellaneous / Electric Bill
  { id: "e027", vendorId: "v007", category: "Electricity", amount: 36500, cgst: 0, sgst: 0, igst: 0, invoiceNumber: "CESC/FEB/2025", invoiceFile: "cesc_feb.pdf", date: "2025-02-08", description: "CESC electricity bill - February 2025", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "Miscellaneous", accountLeaf: "Electric Bill" },
  // e028 — Clinical Posting → College Expense / College Paperwork / Eco Hospital
  { id: "e028", vendorId: "v004", category: "Clinical Posting", amount: 50000, cgst: 2500, sgst: 2500, igst: 0, invoiceNumber: "AMRI/2025/1145", invoiceFile: "amri_1145.pdf", date: "2025-02-20", description: "Clinical posting charges Q3 - AMRI Dhakuria", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "College Paperwork", accountLeaf: "Eco Hospital" },
  // e029 — Clinical Posting → College Expense / College Paperwork / Eco Hospital
  { id: "e029", vendorId: "v005", category: "Clinical Posting", amount: 42000, cgst: 2100, sgst: 2100, igst: 0, invoiceNumber: "ILS/2025/0512", invoiceFile: "ils_0512.pdf", date: "2025-03-15", description: "Clinical posting charges Q3 - ILS Howrah", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "College Paperwork", accountLeaf: "Eco Hospital" },
  // e030 — Mess / Catering → Hostel Expense / Grocery
  { id: "e030", vendorId: "v001", category: "Mess / Catering", amount: 93000, cgst: 4650, sgst: 4650, igst: 0, invoiceNumber: "MTC/2024-25/0248", invoiceFile: "invoice_0248.pdf", date: "2025-03-05", description: "Hostel mess charges - February 2025", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "Hostel Expense", accountSubHead: "Grocery" },
  // e031 — Electricity → College Expense / Miscellaneous / Electric Bill
  { id: "e031", vendorId: "v007", category: "Electricity", amount: 35200, cgst: 0, sgst: 0, igst: 0, invoiceNumber: "CESC/MAR/2025", invoiceFile: "cesc_mar.pdf", date: "2025-03-08", description: "CESC electricity bill - March 2025", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "Miscellaneous", accountLeaf: "Electric Bill" },
  // e032 — Printing (exam stationery) → College Expense / Purchase / Stationery
  { id: "e032", vendorId: "v009", category: "Printing", amount: 18000, cgst: 900, sgst: 900, igst: 0, invoiceNumber: "MP/2025/0089", invoiceFile: "invoice_0089.pdf", date: "2025-03-20", description: "Examination stationery and answer booklets", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "Purchase", accountLeaf: "Stationery" },
  // e033 — Lab Supplies → College Expense / Purchase / Lab Consumables
  { id: "e033", vendorId: "v002", category: "Lab Supplies", amount: 38500, cgst: 1925, sgst: 1925, igst: 0, invoiceNumber: "SLS/2025/0189", invoiceFile: "invoice_0189.pdf", date: "2025-04-02", description: "Biochemistry lab supplies Q4", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "Purchase", accountLeaf: "Lab Consumables" },
  // e034 — Mess / Catering → Hostel Expense / Grocery
  { id: "e034", vendorId: "v001", category: "Mess / Catering", amount: 90000, cgst: 4500, sgst: 4500, igst: 0, invoiceNumber: "MTC/2025-26/0001", invoiceFile: "invoice_001.pdf", date: "2025-04-05", description: "Hostel mess charges - March 2025", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "Hostel Expense", accountSubHead: "Grocery" },
  // e035 — Electricity → College Expense / Miscellaneous / Electric Bill
  { id: "e035", vendorId: "v007", category: "Electricity", amount: 33800, cgst: 0, sgst: 0, igst: 0, invoiceNumber: "CESC/APR/2025", invoiceFile: "cesc_apr.pdf", date: "2025-04-08", description: "CESC electricity bill - April 2025", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "Miscellaneous", accountLeaf: "Electric Bill" },
  // e036 — Security → College Expense / Purchase / Office Supplies
  { id: "e036", vendorId: "v010", category: "Security", amount: 32000, cgst: 1600, sgst: 1600, igst: 0, invoiceNumber: "GS/2025/0078", invoiceFile: "gs_0078.pdf", date: "2025-04-01", description: "Security services - April 2025", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "Purchase", accountLeaf: "Office Supplies" },
  // e037 — Telecommunications → College Expense / Miscellaneous / Visit Expenses
  { id: "e037", vendorId: "v006", category: "Telecommunications", amount: 6100, cgst: 549, sgst: 549, igst: 0, invoiceNumber: "BSNL/APR/2025", invoiceFile: "bsnl_apr.pdf", date: "2025-04-10", description: "BSNL broadband and telephone - April 2025", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "Miscellaneous", accountLeaf: "Visit Expenses" },
  // e038 — Mess / Catering → Hostel Expense / Grocery
  { id: "e038", vendorId: "v001", category: "Mess / Catering", amount: 94000, cgst: 4700, sgst: 4700, igst: 0, invoiceNumber: "MTC/2025-26/0018", invoiceFile: "invoice_018.pdf", date: "2025-05-05", description: "Hostel mess charges - April 2025", status: "Approved", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "Hostel Expense", accountSubHead: "Grocery" },
  // e039 — Lab Supplies → College Expense / Purchase / Lab Consumables
  { id: "e039", vendorId: "v002", category: "Lab Supplies", amount: 29500, cgst: 1475, sgst: 1475, igst: 0, invoiceNumber: "SLS/2025/0267", invoiceFile: "invoice_0267.pdf", date: "2025-04-28", description: "Nursing Fundamentals lab setup - new batch", status: "Pending", submittedBy: "Bikash Sharma", accountBranch: "College Expense", accountSubHead: "Purchase", accountLeaf: "Lab Consumables" },
  // e040 — Pharmacy / Medical → Hostel Expense / Medicine
  { id: "e040", vendorId: "v008", category: "Pharmacy / Medical", amount: 24000, cgst: 1200, sgst: 1200, igst: 0, invoiceNumber: "EP/2025/0156", invoiceFile: "ep_0156.pdf", date: "2025-04-30", description: "Medical supplies for clinical simulation lab", status: "Pending", submittedBy: "Bikash Sharma", accountBranch: "Hostel Expense", accountSubHead: "Medicine" },

  // ── NEW ENTRIES e041–e050 ──────────────────────────────────────────────────

  // e041 — Infrastructure / Building / Civil Work — vendor: Rajesh Construction
  { id: "e041", vendorId: "v012", category: "Construction", amount: 185000, cgst: 16650, sgst: 16650, igst: 0, invoiceNumber: "CONST/2024/1025", invoiceFile: "const_1025.pdf", date: "2024-10-25", description: "Classroom extension - ground floor civil work", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "Infrastructure", accountSubHead: "Building", accountLeaf: "Civil Work" },

  // e042 — College Expense / College Salary / Teacher Salary — DIRECT PAYMENT (no vendor)
  { id: "e042", isDirectPayment: true, category: "Salary", amount: 240000, cgst: 0, sgst: 0, igst: 0, invoiceNumber: "SAL/OCT/2024/FAC", date: "2024-10-31", description: "Faculty salary disbursement - October 2024", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "College Salary", accountLeaf: "Teacher Salary" },

  // e043 — College Expense / College Transport / Bus — vendor: Eastern Transport
  { id: "e043", vendorId: "v014", category: "Transport", amount: 18500, cgst: 1665, sgst: 1665, igst: 0, invoiceNumber: "TRN/2024/0311", invoiceFile: "trn_0311.pdf", date: "2024-11-10", description: "Bus fuel and maintenance - Q2", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "College Transport", accountLeaf: "Bus" },

  // e044 — College Expense / Advertisement / Online Advertisement — vendor: Digital Spark
  { id: "e044", vendorId: "v013", category: "Advertisement", amount: 12000, cgst: 1080, sgst: 1080, igst: 0, invoiceNumber: "ADV/2024/0118", invoiceFile: "adv_0118.pdf", date: "2024-11-18", description: "Facebook & Instagram ads - admission campaign", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "Advertisement", accountLeaf: "Online Advertisement" },

  // e045 — Infrastructure / Building / Electric Work — vendor: Rajesh Construction
  { id: "e045", vendorId: "v012", category: "Construction", amount: 45000, cgst: 4050, sgst: 4050, igst: 0, invoiceNumber: "ELEC/2025/0120", invoiceFile: "elec_0120.pdf", date: "2025-01-20", description: "New electrical wiring - first floor", status: "Approved", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "Infrastructure", accountSubHead: "Building", accountLeaf: "Electric Work" },

  // e046 — College Expense / College Salary / Teacher Salary — DIRECT PAYMENT
  { id: "e046", isDirectPayment: true, category: "Salary", amount: 240000, cgst: 0, sgst: 0, igst: 0, invoiceNumber: "SAL/JAN/2025/FAC", date: "2025-01-31", description: "Faculty salary disbursement - January 2025", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "College Salary", accountLeaf: "Teacher Salary" },

  // e047 — Hostel Expense / Salary — DIRECT PAYMENT
  { id: "e047", isDirectPayment: true, category: "Salary", amount: 65000, cgst: 0, sgst: 0, igst: 0, invoiceNumber: "SAL/FEB/2025/HST", date: "2025-02-28", description: "Hostel warden and cook salary - February 2025", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "Hostel Expense", accountSubHead: "Salary" },

  // e048 — College Expense / Book Account / Anand Books Kolkata — vendor: Anand Books
  { id: "e048", vendorId: "v011", category: "Books", amount: 22500, cgst: 2025, sgst: 2025, igst: 0, invoiceNumber: "ANAND/2025/0310", invoiceFile: "anand_0310.pdf", date: "2025-03-10", description: "Nursing textbooks for new GNM batch", status: "Paid", submittedBy: "Bikash Sharma", approvedBy: "Dr. Pratima Ghosh", accountBranch: "College Expense", accountSubHead: "Book Account", accountLeaf: "Anand Books Kolkata" },

  // e049 — College Expense / College Paperwork / WBNC & INC — DIRECT PAYMENT (govt fee)
  { id: "e049", isDirectPayment: true, category: "Paperwork", amount: 38000, cgst: 0, sgst: 0, igst: 0, invoiceNumber: "INC/2025/0415", invoiceFile: "inc_0415.pdf", date: "2025-04-15", description: "INC affiliation renewal fee 2025-26", status: "Pending", submittedBy: "Bikash Sharma", accountBranch: "College Expense", accountSubHead: "College Paperwork", accountLeaf: "WBNC & INC" },

  // e050 — Infrastructure / Building / Construction Work — vendor: Rajesh Construction
  { id: "e050", vendorId: "v012", category: "Construction", amount: 320000, cgst: 28800, sgst: 28800, igst: 0, invoiceNumber: "CONST/2025/0422", invoiceFile: "const_0422.pdf", date: "2025-04-22", description: "Hostel block - 2nd floor slab casting", status: "Pending", submittedBy: "Bikash Sharma", accountBranch: "Infrastructure", accountSubHead: "Building", accountLeaf: "Construction Work" },
];
