import { Vendor } from "../types";

export const mockVendors: Vendor[] = [
  {
    id: "v001",
    name: "Maa Tara Caterers",
    gstin: "19AABCM1234A1ZK",
    address: "12 Beliaghata Main Road, Kolkata 700010",
    contact: "9831500001",
    email: "maatara.catering@gmail.com",
    category: "Catering / Mess",
    paymentTerms: "Net 30",
    accountHeads: ["Grocery", "Vegetables", "Chicken", "Fish", "Rice", "Gas / Firewood", "Tiffin", "Cooking Materials"],
  },
  {
    id: "v002",
    name: "Salt Lake Lab Solutions",
    gstin: "19AABCS2345B1ZL",
    address: "CF-56 Salt Lake Sector III, Kolkata 700091",
    contact: "9831500002",
    email: "saltlake.lab@gmail.com",
    category: "Lab Supplies",
    paymentTerms: "Net 15",
    accountHeads: ["Purchase"],
  },
  {
    id: "v003",
    name: "Newtown Stationery",
    gstin: "19AABCN3456C1ZM",
    address: "Action Area II, Newtown, Kolkata 700135",
    contact: "9831500003",
    email: "newtown.stationery@gmail.com",
    category: "Stationery & Books",
    paymentTerms: "Immediate",
    accountHeads: ["Purchase", "Book Account"],
  },
  {
    id: "v004",
    name: "AMRI Hospitals",
    gstin: "19AABCA4567D1ZN",
    address: "58 Gariahat Road, Dhakuria, Kolkata 700029",
    contact: "033-30588601",
    email: "clinical@amrihospitals.com",
    category: "Clinical Posting",
    paymentTerms: "Net 60",
    accountHeads: ["College Paperwork"],
  },
  {
    id: "v005",
    name: "ILS Hospitals Howrah",
    gstin: "19AABCI5678E1ZO",
    address: "P-4 CIT Scheme LXXII, Howrah 711114",
    contact: "033-23030000",
    email: "billing@ilshospitals.com",
    category: "Clinical Posting",
    paymentTerms: "Net 60",
    accountHeads: ["College Paperwork"],
  },
  {
    id: "v006",
    name: "BSNL West Bengal Circle",
    gstin: "19AABCB6789F1ZP",
    address: "Bharat Sanchar Bhavan, Wood Street, Kolkata 700016",
    contact: "1800-345-1500",
    email: "pgm.wb@bsnl.co.in",
    category: "Telecommunications",
    paymentTerms: "Due on Receipt",
    accountHeads: ["Miscellaneous"],
  },
  {
    id: "v007",
    name: "CESC Limited",
    gstin: "19AABCC7890G1ZQ",
    address: "CESC House, Chowringhee Square, Kolkata 700001",
    contact: "033-22251234",
    email: "commercial@cesc.co.in",
    category: "Electricity",
    paymentTerms: "Due on Receipt",
    accountHeads: ["Miscellaneous"],
  },
  {
    id: "v008",
    name: "Eden Pharmacy",
    gstin: "19AABCE8901H1ZR",
    address: "23 Shakespeare Sarani, Kolkata 700017",
    contact: "9831500008",
    email: "eden.pharmacy@gmail.com",
    category: "Pharmacy / Medical",
    paymentTerms: "Net 15",
    accountHeads: ["Medicine"],
  },
  {
    id: "v009",
    name: "Modern Press & Printers",
    gstin: "19AABCM9012I1ZS",
    address: "45 Mechua Bazar Street, Kolkata 700007",
    contact: "9831500009",
    email: "modern.press@gmail.com",
    category: "Printing",
    paymentTerms: "Immediate",
    accountHeads: ["Advertisement", "Purchase"],
  },
  {
    id: "v010",
    name: "Globe Security Services",
    gstin: "19AABCG0123J1ZT",
    address: "78 Nizam Palace, AJC Bose Road, Kolkata 700017",
    contact: "9831500010",
    email: "globe.security@gmail.com",
    category: "Security",
    paymentTerms: "Net 30",
    accountHeads: ["Purchase"],
  },
  {
    id: "v011",
    name: "Anand Books, Kolkata",
    gstin: "19AABCA1111K1ZU",
    address: "College Street, Kolkata 700073",
    contact: "9831500011",
    email: "anandbooks.kolkata@gmail.com",
    category: "Books & Publications",
    paymentTerms: "Immediate",
    accountHeads: ["Book Account"],
  },
  {
    id: "v012",
    name: "Rajesh Construction Co.",
    gstin: "19AABCR2222L1ZV",
    address: "14 Ultadanga Main Road, Kolkata 700067",
    contact: "9831500012",
    email: "rajesh.construction@gmail.com",
    category: "Civil / Construction",
    paymentTerms: "Net 45",
    accountHeads: ["Building"],
  },
  {
    id: "v013",
    name: "Digital Spark Agency",
    gstin: "19AABCD3333M1ZW",
    address: "Salt Lake Sector V, Kolkata 700091",
    contact: "9831500013",
    email: "digitalspark@gmail.com",
    category: "Digital Marketing",
    paymentTerms: "Net 15",
    accountHeads: ["Advertisement"],
  },
  {
    id: "v014",
    name: "Eastern Transport Services",
    gstin: "19AABCE4444N1ZX",
    address: "35 Kankurgachi, Kolkata 700054",
    contact: "9831500014",
    email: "eastern.transport@gmail.com",
    category: "Transport",
    paymentTerms: "Immediate",
    accountHeads: ["College Transport"],
  },
];
